### ISSUE TITLE
Issues with Windows Instructions

### ISSUE THREAD

**Issue by walllable** [Roachbones/discordless#10]
Hi - having a problem where I can't start the proxy server. I get this output when I run the command provided.

`K:\discord backups\discordless\discordless>mitmdump -s wumpus_in_the_middle.py --listen-port=8080 --allow-hosts '^(((.+\.)?discord\.com)|((.+\.)?discordapp\.com)|((.+\.)?discord\.net)|((.+\.)?discordapp\.net)|((.+\.)?discord\.gg))$'
?discordapp\.com was unexpected at this time.`

I have python 3.10.6 installed, and mitmproxy installed correctly.

EDIT: It's because `'^(((.+\.)?discord\.com)|((.+\.)?discordapp\.com)|((.+\.)?discord\.net)|((.+\.)?discordapp\.net)|((.+\.)?discord\.gg))$'` uses single quotes/apostrophes and not " double quotes.
Also while I'm here, `mitmproxy` is misspelled as `mitproxy`

**Comment by Roachbones** [comment]
Thanks for reporting this, should be fixed now! Cute avatar btw!
