### ISSUE TITLE
mitmproxy crashes due to Unexpected event type at HttpStream._handle_event

### ISSUE THREAD

**Issue by youbananapeel** [Roachbones/discordless#13]
I might be missing some program that wasn't listed in the tutorial, but whenever I try to run discordless on windows, mitmproxy crashes.
I followed all the steps and it gives me the error `AssertionError: Unexpected event type at HttpStream._handle_event: Expected Start|HttpEvent, got Reply(WebsocketStartHook(flow=<HTTPFlow`  in the wumpus_in_the_middle.py command.
Is there a way to fix this?
![Screenshot 2024-01-07 130032](https://github.com/Roachbones/discordless/assets/155914070/fac2def6-12f3-4242-956e-29791b2a940d)

**Comment by Roachbones** [comment]
Never seen that before! I'd try these two things:

- If you haven't already, try closing Discord completely, _then_ running the wumpus_in_the_middle.py command, then opening Discord while mitmproxy is running. (Maybe mitmproxy is getting confused about starting in the middle of an existing websocket connection?)
- If that doesn't work, try just running mitmproxy without wumpus_in_the_middle.py (just remove ` -s wumpus_in_the_middle.py` from the command) and see if it still crashes. If it does, maybe it's just a mitmproxy bug and not Discordless's fault.

**Comment by youbananapeel** [comment]
Closing Discord completely helps me run the program, but doing that still has mitmproxy crashing
However, I removed `-s wumpus_in_the_middle.py` and it still crashed, so i think this is a mitmproxy bug instead of Discordless. I'll try reinstalling a different version of mitmproxy to see if the bug is fixed.

**Comment by youbananapeel** [comment]
I've switched from the newest version of mitmproxy to 10.0.0, and mitmproxy doesnt crash and Discordless now runs normally.
