### ISSUE TITLE
Embed author icons not working

### ISSUE THREAD

**Issue by Roachbones** [Roachbones/discordless#6]
The icon specified by `iconUrl` in an embed's `author` isn't showing up in DCEF. Not sure why. Tried printing the message object to console in DCEF, but that option does not seem to do anything.

**Comment by slatinsky** [comment]
Fixed in the latest DCEF [release v2.3.1](https://github.com/slatinsky/DiscordChatExporter-frontend/releases/tag/v2.3.1). All hotlinked (online) assets didn't load, not just `iconUrl`.

Also you can see printed message object in devtools console (F12 in Chrome).

**Comment by slatinsky** [comment]
This will be added later to DCEF with other special messages like guild joins.

In the future it is better to raise an issue in [DiscordChatExporter-frontend](https://github.com/slatinsky/DiscordChatExporter-frontend) repo.

**Comment by Roachbones** [comment]
Cool, I wasn't sure if the problem was with Discordless or DCEF :slightly_smiling_face:
